"""add table articles

Revision ID: d6e4de61c58f
Revises: 
Create Date: 2017-09-22 08:21:29.211711+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e4de61c58f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=255), nullable=False),
        sa.Column('realm_id', sa.Integer()),
        sa.Column('realm_name', sa.String(length=255)),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('view_num', sa.Integer(), nullable=False),
        sa.Column('comment_num', sa.Integer(), nullable=False),
        sa.Column('published_at', sa.DateTime(), nullable=False),
        sa.Column('published_by', sa.Integer(), nullable=False),
        sa.Column('banana_num', sa.Integer(), nullable=True),
        sa.Column('is_get_comments', sa.Boolean(), nullable=True, server_default=sa.text('FALSE')),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
