"""add table users

Revision ID: 4a0e162711e1
Revises: a397ee7e8d23
Create Date: 2017-09-25 23:00:14.664076+08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

import os, sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))
from db import Session

sesson = Session()

# revision identifiers, used by Alembic.
revision = '4a0e162711e1'
down_revision = 'a397ee7e8d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sign', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('post_num', sa.Integer(), nullable=True),
    sa.Column('post_article_num', sa.Integer(), nullable=True),
    sa.Column('post_video_num', sa.Integer(), nullable=True),
    sa.Column('come_from', sa.String(length=255), nullable=True),
    sa.Column('last_login_ip', sa.String(length=255), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('fans_num', sa.Integer(), nullable=True),
    sa.Column('follow_num', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('register_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    upgrade_data()
    # ### end Alembic commands ###

def upgrade_data():
    sesson.execute(text('INSERT INTO users(id) SELECT DISTINCT published_by from articles'))
    sesson.commit()
    sesson.close()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
