"""add crawl_comments to articles

Revision ID: a7bfa0f5a3a3
Revises: 9e328ab68d0f
Create Date: 2017-10-11 00:06:39.697616+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bfa0f5a3a3'
down_revision = '9e328ab68d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('crawl_comments', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'crawl_comments')
    # ### end Alembic commands ###
