"""add banana num to article

Revision ID: a397ee7e8d23
Revises: d6e4de61c58f
Create Date: 2017-09-24 14:38:57.395430+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a397ee7e8d23'
down_revision = 'd6e4de61c58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('banana_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'banana_num')
    # ### end Alembic commands ###
