"""add latestCommentTime to content

Revision ID: 9ab046e9e03d
Revises: c4162b413189
Create Date: 2018-10-25 22:39:20.157002+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab046e9e03d'
down_revision = 'c4162b413189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('latest_comment_time', sa.String(length=255)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'latest_comment_time')
    # ### end Alembic commands ###
