"""add channel id to contents

Revision ID: c0d512bb9fa1
Revises: 5ee6d18e50ed
Create Date: 2018-03-11 18:22:20.429586+08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0d512bb9fa1'
down_revision = '5ee6d18e50ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('channel_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'channel_id')
    # ### end Alembic commands ###
